version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Berlin
    rebase-strategy: disabled
    ignore:
      - dependency-name: '@babel/*'
        versions:
          - '^8.0.0'
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'browserslist'
      eslint:
        patterns:
          - '@eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'typescript-eslint'
