changesetBaseRefs:
  - v0.1.10

changesetIgnorePatterns:
  - .*
  - .*/**
  - '**/package.json'
  - README.md
  - yarn.lock
  - '**/*.test.{js,ts}'

nodeLinker: node-modules

unsafeHttpWhitelist:
  - localhost
