approvedGitRepositories:
  - 'https://github.com/laboperator-gmbh/**'
  - 'ssh://git@github.com/laboperator-gmbh/**'

changesetBaseRefs:
  - v0.2.1

changesetIgnorePatterns:
  - .*
  - .circleci/**
  - .github/**
  - CODEOWNERS
  - CONTRIBUTING.md
  - README.md
  - yarn.lock
  - '**/package.json'
  - '**/*.test.{js,ts}'

enableScripts: true
nodeLinker: node-modules
npmMinimalAgeGate: 3d
unsafeHttpWhitelist:
  - localhost
