changesetBaseRefs:
  - v0.2.1

changesetIgnorePatterns:
  - .*
  - .circleci/**
  - .github/**
  - CODEOWNERS
  - CONTRIBUTING.md
  - README.md
  - yarn.lock
  - '**/package.json'
  - '**/*.test.{js,ts}'

nodeLinker: node-modules

unsafeHttpWhitelist:
  - localhost
